spring.application.name=SpringBatch
# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/batchdb
spring.datasource.username=root
spring.datasource.password=user
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
#ye line hibernate ko database ke schema ko update karne ke liye set kiya gaya hai, isse existing tables ko drop nahi karega aur naye tables create karega.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#This tells Spring Batch to always initialize its metadata tables (like BATCH_JOB_INSTANCE,
#BATCH_JOB_EXECUTION, etc.) in the database when the application starts.
#ye line job ke liye metadata tables ko initialize karne ke liye hai, isse hamesha initialize karne ke liye set kiya gaya hai.
spring.batch.jdbc.initialize-schema=always


# ye line job ko manually trigger karne ke liye hai, isse false set karne par job automatically start nahi hoga.
spring.batch.job.enabled=true
server.port=9090
